name        : vapoursynth
version     : 32
release     : 1
source      :
    - https://github.com/vapoursynth/vapoursynth/archive/R32.tar.gz : e9560f64ba298c2ef9e6e3d88f63ea0ab88e14bbd0e9feee9c621b9224e408c8
license     :
    - OFL-1.1
    - LGPL-2.1+
component   : multimedia.library
summary     : A video processing framework with simplicity in mind.
description : |
    VapourSynth is an application for video manipulation. Or a plugin. Or a library.
    It’s hard to tell because it has a core library written in C++ and a Python module to allow video scripts to be created.
setup      : |
    %autogen
    %configure --enable-imwri --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/vapoursynth.xml $installdir/usr/share/mime/packages/vapoursynth.xml
